### ISSUE TITLE
Create a hex sticker

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiraldata#15]
### Background Information

hex sticker for `admiraldata`

**Comment by PoojaKumari05** [comment]
Hi @kaz462 @manciniedoardo - I have created the hex sticker via [hexmake (thinkr.fr)](https://connect.thinkr.fr/hexmake/) and kept the color as "Yellow" as suggested by @bms63 which denotes 'construction' - since this package helps us build vignettes and examples. Kindly review and let me know which yellow is good to go.  

![hex_admiraldata_2](https://github.com/pharmaverse/admiraldata/assets/90273880/68fd82dc-d36d-45c6-b0a9-66f152ece6a5)
![hex_admiraldata_1](https://github.com/pharmaverse/admiraldata/assets/90273880/4e8699e1-1951-44cc-99dd-73a74e3887bb)

**Comment by kaz462** [comment]
Agreed during the meeting: darker one

**Comment by kaz462** [comment]
@PoojaKumari05 Thanks a lot for working on this, looks awesome!
